before_install:
- wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
- tar -xvf SDL2-2.0.5.tar.gz
- cd SDL2-2.0.5.tar.gz
- ./configure && make && sudo make install
script:
- mkdir build
- cd build
- cmake .. && make && make test