language: cpp
compiler: g++
before_install:
- wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
- tar -xvf SDL2-2.0.5.tar.gz
- cd SDL2-2.0.5
- ./configure && make && sudo make install
- cd ..
- wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
- tar -xvf SDL2_image-2.0.1.tar.gz
- cd SDL2_image-2.0.1
- ./configure && make && sudo make install
- cd ..
install:
- mkdir build
- cd build
- cmake .. && make
- cd ..
script:
- cd build
- make test
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - g++-4.9
        - libgtest0
        - libgtest-dev